import Head from 'next/head'
import 'tailwindcss/tailwind.css'
import { useEffect, useState } from 'react';
import Bookmarks from '../components/bookmarks'
import Card from '../components/Card'
import Handle from '../components/Handle'
import Insert from '../components/Insert'
import BookmarkContext from '../lib/context'
import { cacheGet, cacheUpdate, checkCache } from '../lib/cache';

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [cacheReady, setCacheReady] = useState(false);
  const [bookmarks, setBookmarks] = useState([]);

  useEffect(() => {
    const isCache = checkCache(window)
    setCacheReady(isCache)
    if (isCache) {
      setLoading(true)
      cacheGet()
        .then(bmks => {
          setBookmarks(bmks || [])
        })
        .finally(() => setLoading(false))
    } else {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    if (!loading  && checkCache(window)) {
      cacheUpdate(bookmarks)
      .then(() => {})
    }
  }, [loading, bookmarks])

  const onClear = () => setBookmarks([])

  const loadingPage = <>
    <h1 className="text-xl md:text-6xl text-black uppercase m-8">Loading...</h1>
  </>

  const errorPage = <>
    <h1 className="text-xl md:text-6xl text-black uppercase m-8">Cache unavailable :(</h1>
  </>

  const bookmarkPage = <>
    <BookmarkContext.Provider value={{ bookmarks, setBookmarks }}>
        <h1 className="text-4xl md:text-6xl text-black uppercase m-8">B O O K M A R K S</h1>
        <Card>
            <Bookmarks/>
        </Card>
        <Card>
            <Insert/>
        </Card>
        <Card>
          <div className="mb-3">
            Clear all bookmarks
          </div>
          <button className="bg-red-200 rounded p-2 hover:bg-red-400 h-min mb-1" onClick={onClear}>
            clear
          </button>
        </Card>
        <Handle/>
    </BookmarkContext.Provider>
  </>

  let page
  if (loading) {
    page = loadingPage
  } else if (cacheReady) {
    page = bookmarkPage
  } else {
    page = errorPage
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container mx-auto flex justify-center items-center flex-col text-center">
          {page}
        </div>
      </main>
    </div>
  )
}
