import Head from 'next/head'
import 'tailwindcss/tailwind.css'
import { useEffect, useState } from 'react';
import Bookmarks from '../components/bookmarks'
import Card from '../components/Card'
import Handle from '../components/Handle'
import Insert from '../components/Insert'
import BookmarkContext from '../lib/context'
import { checkCache } from '../lib/cache';

export default function Home() {
  const [cacheReady, setCacheReady] = useState(false);
  const [bookmarks, setBookmarks] = useState(["fawfawfa","fawfawfa","fawfawfa"]);

  useEffect(() => setCacheReady(checkCache(window)), [])

  const onClear = () => setBookmarks([])

  const errorPage = <>
    <h1 className="text-xl md:text-6xl text-black uppercase m-8">Cache unavailable :(</h1>
  </>

  const bookmarkPage = <>
    <BookmarkContext.Provider value={{ bookmarks, setBookmarks }}>
        <h1 className="text-4xl md:text-6xl text-black uppercase m-8">B O O K M A R K S</h1>
        <Card>
            <Bookmarks/>
        </Card>
        <Card>
            <Insert/>
        </Card>
        <Card>
          <div className="mb-3">
            Clear all bookmarks
          </div>
          <button className="bg-red-200 rounded p-2 hover:bg-red-400 h-min mb-1" onClick={onClear}>
            clear
          </button>
        </Card>
        <Handle/>
    </BookmarkContext.Provider>
  </>

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container mx-auto flex justify-center items-center flex-col text-center">
          {cacheReady ? bookmarkPage : errorPage}
        </div>
      </main>
    </div>
  )
}
